apiVersion: v1
kind: Service
metadata:
  name: mywebapp
  labels:
    run: mywebapp
spec:
  type: LoadBalancer
  ports:
    - port: 80           # map port 80 in the service to the container port 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    run: mywebapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp
spec:
  replicas: 3
  selector:
    matchLabels:
      run: mywebapp
  template:
    metadata:
      labels:
        run: mywebapp
    spec:
      containers:
        - name: mysql
          image: mysql
          env:
            - name: MYSQL_DATABASE
              value: myDB
            - name: MYSQL_ROOT_PASSWORD
              value: password            # set MYSQL_ROOT_PASSWORD to password and MYSQL_DATABASE to myDB 
          ports:
            - containerPort: 3306       # expose the MySQL default port
        - name: webapp
          image: us.gcr.io/index-cloudcomputing/webapp:version1            # set the image name
          ports:
            - containerPort: 8080